DELIMITER :)
DROP PROCEDURE IF EXISTS getISODate :)

CREATE PROCEDURE getISODate(OUT isodate VARCHAR(8))
BEGIN
	SET isodate = (SELECT CONCAT(YEAR(NOW())
		,IF(LENGTH(MONTH(NOW())) = 2,MONTH(NOW()),CONCAT('0',MONTH(NOW())))
		,IF(LENGTH(DAY(NOW())) = 2,DAY(NOW()),CONCAT('0',DAY(NOW())))));
END :)

DELIMITER ;